spring:
  datasource:
    url: jdbc:mysql://localhost:3307/testdb
    username: root
    password: mani@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: data-collection
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8085
springdoc:
  swagger-ui:
    path: swagger-ui.html