spring:
  datasource:
    url: jdbc:mysql://localhost:3307/testdb
    username: root
    password: mani@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: user-api
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: gopikrishnaboppudi786@gmail.com
    password: wiuo bfxl ebgu dlen
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8083
springdoc:
  swagger-ui:
    path: swagger-ui.html
